apiVersion: v1
kind: Pod
metadata:
  name: myapp-php
spec:
  containers:
    - name: myapp-php
      image: thiagost32/myapp-php:1.0
      ports: 
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-php-service
spec:
  type: NodePort
  selector:
    app: myapp-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31012 